LMS/LMS/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.models import User

from django_otp.admin import OTPAdminSite
from django_otp.plugins.otp_totp.models import TOTPDevice
from django_otp.plugins.otp_totp.admin import TOTPDeviceAdmin

class OTPAdmin(OTPAdminSite):
    pass

# Create an instance of your custom admin site
admin_site = OTPAdmin(name='OTPAdmin')

# Register User and TOTPDevice with your custom admin site
admin_site.register(User)
admin_site.register(TOTPDevice, TOTPDeviceAdmin)

urlpatterns = [
    path('admin/', admin_site.urls),  # Use your custom admin site
    path('dadmin/', admin.site.urls),  # Use the default admin site
    path('', include('lmsapp.urls')),
]

LMS/lmsapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.dispatch import receiver
from ckeditor.fields import RichTextField


# Create your models here.
class User(AbstractUser): 
    STATUS = (
        ('STUDENT','STUDNET'),        
        ('PENDING', 'PENDING'),
        ('INSTRUCTOR', 'INSTRUCTOR'),
    )   
    profile_image = models.ImageField(upload_to="Images/profile", null=True, blank=True, default='img/team-1.jpg')
    is_manager = models.BooleanField('Is manager', default=False)
    is_instructor = models.BooleanField('Is instructor', default=False)
    is_student = models.BooleanField('Is student', default=True)
    user_bio = models.TextField(default='', max_length=200, null=True, blank=True)
    email_token = models.UUIDField(default=uuid.uuid4, editable=False)
    is_verified = models.BooleanField(default=False)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    status = models.CharField(choices=STATUS,max_length=100,null=True, default="STUDENT")

    def account_detail_url(self):
        from django.urls import reverse
        return reverse("accdetails", kwargs={'slug': self.slug})

class Categories (models.Model):
    icon = models.CharField(max_length=200, null=True)
    name = models.CharField(max_length=100)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    def __str__(self):
        return self.name

class Course(models.Model): 
    STATUS = (
        ('PUBLISH','PUBLISH'),
        ('DRAFT', 'DRAFT'),        
        ('PENDING', 'PENDING'),
    )
    title = models.CharField(max_length=500)
    date = models.DateField(auto_now_add=True)
    featured_image = models.ImageField(upload_to="Images/Featured_Image/featured_img",null=True, blank=True)
    instructor = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    category = models.ForeignKey(Categories,on_delete=models.CASCADE)
    featured_video = models.CharField(max_length=300,null=True)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    status = models.CharField(choices=STATUS,max_length=100,null=True)
    description = RichTextField(blank=True, null=True)
    price = models.IntegerField(null=True,default=0)
    discount = models.IntegerField(null=True)

    def __str__(self):
        return self.title
    
    def course_url(self):
        from django.urls import reverse
        return reverse("coursedetails", kwargs={'slug': self.slug})

    def checkout_url(self):
        from django.urls import reverse
        return reverse("checkout", kwargs={'slug': self.slug})

    def cart_url(self):
        from django.urls import reverse
        return reverse("cart", kwargs={'slug': self.slug})

    def edit_course_url(self): 
        from django.urls import reverse
        return reverse("editcourse", kwargs={'slug': self.slug})

    def learning_area_url(self): 
        from django.urls import reverse
        return reverse("learning_area", kwargs={'slug': self.slug})

    def add_lesson_url(self): 
        from django.urls import reverse
        return reverse("add_lesson", kwargs={'slug': self.slug})

    


class Blog(models.Model):
    STATUS = (
        ('PUBLISH','PUBLISH'),
        ('DRAFT', 'DRAFT'),
        ('PENDING', 'PENDING'),
    )
    title = models.CharField(max_length=500)
    date = models.DateField(auto_now_add=True)
    featured_image = models.ImageField(upload_to="Images/Featured_Image/Blog",null=True, blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    category = models.ForeignKey(Categories,on_delete=models.CASCADE)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    status = models.CharField(choices=STATUS,max_length=100,null=True)
    description = RichTextField(blank=True, null=True)
    

    def __str__(self):
        return self.title

    def edit_blog_url(self):
        from django.urls import reverse
        return reverse("editblog", kwargs={'slug': self.slug})
    
    def blog_url(self):
        from django.urls import reverse
        return reverse("blogdetails", kwargs={'slug': self.slug})



# ==================================slug creator=======================
def create_slug(instance, new_slug=None):
    if isinstance(instance, (Course, Blog)):
        source_field = 'title'
    elif isinstance(instance, User):
        source_field = 'username'
    elif isinstance(instance, Categories):
        source_field = 'name'
    else:
        raise ValueError("Unsupported model type for slug generation")

    
    slug = slugify(getattr(instance, source_field))

    if new_slug is not None:
        slug = new_slug

    model_class = instance.__class__
    qs = model_class.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()

    if exists:
        new_slug = f"{slug}-{qs.first().id}"
        return create_slug(instance, new_slug=new_slug)
    return slug

@receiver(pre_save, sender=Course)
@receiver(pre_save, sender=Blog)
@receiver(pre_save, sender=Categories)
@receiver(pre_save, sender=User)
def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__ (self):
        return self.name + " - " + self.course.title 

class Video(models.Model):
    serial_number = models.IntegerField(null=True)
    thumbnail = models.ImageField(upload_to="Images/Lesson", null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    title = models.CharField(max_length = 100)
    video_url = models.CharField(max_length= 200)
    time_duration = models.FloatField(null=True)
    preview = models.BooleanField(default=False) 

    def __str__(self):
        return self.title


class DigitalProduct(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    product_identity = models.IntegerField(null=True,default=0)
    product_name = models.CharField(max_length=255)
    transaction_id = models.CharField(max_length=255, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    mobile = models.CharField(max_length=15, default="980000000", null=True) 

    def __str__(self):
        return f'{self.user.username} - {self.product_name} - Transaction ID: {self.transaction_id}'

class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_messages')
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __str__(self):
        return f"{self.sender.username} to {self.receiver.username} - {self.timestamp}"


# Recommendations
class SearchQuery(models.Model):
    query = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.query




# ===========certificate:
class Certificate(models.Model):
    username = models.CharField(max_length=255)
    course_name = models.CharField(max_length=255)
    instructor_name = models.CharField(max_length=255)


# comment
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course_title = models.CharField(max_length=255)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.course_title} - {self.created_at}"

LMS/templates/Student/becomeinstructor.html
{% extends 'components/dashboard/base.html'%} {% load static %} 
{%block content%}
{% if user.is_student %}
<div class="container-fluid py-4 d-flex justify-content-center">

  <div class="row mt-4">
    <div class="col mt-4 mb-3">
      <div class="card z-index-2">
        <div
          class="card-header p-0 position-relative mt-n4 mx-3 z-index-2 bg-transparent">
          <div class="bg-gradient-danger shadow-dark border-radius-lg py-3 pe-1">
            <h4 class="text-white m-3 p-3 text-center">Become Instructor</h4>
          </div>
        </div>
        <div class="card-body d-flex justify-content-center">
          {% if user.status == 'PENDING'%}      
          <button type="button" class="btn bg-gradient-warning btn-lg mt-1 mx-auto">
            Already Applied For Instructor
          </button>
          {% else%}
          <button type="button" class="btn bg-gradient-success btn-lg mt-1 mx-auto" data-bs-toggle="modal" data-bs-target="#publish_modal">
            Apply For Instructor
          </button>
          {% endif %}
          {% comment %} ===modal {% endcomment %}
          <div class="modal fade" id="publish_modal" tabindex="-1" role="dialog" aria-labelledby="publish_modalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="publish_modalLabel">Apply For Instructor</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <p>Are you sure want to Become Instructor?</p>
                  <strong>{{i.username}}</strong>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn bg-gradient-danger" data-bs-dismiss="modal">Close</button>
                  <form method="post" action="{% url 'request_instructor' user.id %}">
                    {% csrf_token %}
                  <button type="submit" class="btn bg-gradient-success" data-bs-dismiss="modal">Yes</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
          
        </div>
      </div>
    </div>
  </div>

  
</div>
{% endif %}
{% endblock %}

LMS/templates/Student/dashboard.html
{% extends 'components/dashboard/base.html'%}
{% load static %}
{%block content%}
<div class="row">
  <h3>Continue Learning ...</h3>
  {% for i in enroll %} 
  {% if i.user|striptags|lower == username|striptags|lower %}
    <div class="row">
      <a href="{{i.course.learning_area_url}}">
      <div class="col col-md-6 col-lg-3">
        <div
          class="card card-background card-background-mask-dark align-items-start mt-4">
          <div
            class="full-background cursor-pointer"
            style="
              background-image: url('{{i.course.featured_image.url}}');
            "></div>
          <div class="card-body">
            <h5 class="text-white mb-0">{{i.course.title}}</h5>
            <p class="text-white text-sm">{{i.course.instructor}} </p>
            
          </div>
        </div>
        <div class="progress-wrapper">
          <div class="progress">
            <div
              class="progress-bar bg-primary rounded"
              role="progressbar"
              aria-valuenow="60"
              aria-valuemin="0"
              aria-valuemax="100"
              style="width: 60%"></div>
          </div>
        </div>
      </a>
      </div>
      {% endif %}
      
      {% endfor %}
{% endblock %}

LMS/templates/Student/learning_area.html
{% extends 'components/dashboard/base.html'%} {%block title%}Course Name |
Skylearner {% endblock %} {% block sub_title %}
<h6 class="font-weight-bolder mb-0">My Learning</h6>
{% endblock %} {% load static %} {%block content%}
<div class="container-fluid">
  <div class="row">
    <div class="col-9">
      <div class="embed-responsive embed-responsive-16by9" style>
        <iframe
          id="videoPlayer"
          width="100%"
          height="500"
          src="https://www.youtube.com/embed/jE7c3dDdReQ?si=ogEEsE_NK2k3yL7L"
          title="YouTube video player"
          frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
          allowfullscreen></iframe>
      </div>
      <nav>
        <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
          <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Home</button>
          <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Description</button>
          <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact" type="button" role="tab" aria-controls="nav-contact" aria-selected="false">Quizes/Ressources</button>
          <button class="nav-link" id="certificate-tab" data-bs-toggle="tab" data-bs-target="#certificate" type="button" role="tab" aria-controls="certificate" aria-selected="false">Certificate</button>
          </div>
      </nav>
      <div class="tab-content" id="nav-tabContent">
        <div class="container overflow-auto vh-100 bg-light m-2 p-2 tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
          Comments
   
        </div>
        <div class="container overflow-auto vh-100 bg-light m-2 p-2 tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">{{course.description | safe }}</div>
        <div class="container overflow-auto vh-100 bg-light m-2 p-2 tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">{% include 'Student/quizes.html' %}</div>
        <div class="container overflow-auto vh-100 bg-light m-2 p-2 tab-pane fade" id="certificate" role="tabpanel" aria-labelledby="certificate-tab">
          <form method="post" action="{% url 'generate_certificate' %}">
            {% csrf_token %}
            <input type="hidden" value="{{course.title}}" name='coursename'>
            <input type="hidden" value="{{user.username}}" name='username'>
            <input type="hidden" value="{{course.instructor}}" name='instructor'>
            <button type="submit" class="btn btn-primary btn-lg">Generate Certificate</button>
        </form>
        </div>
      </div>
    </div>
    <div class="col-3 bg-dark text-white overflow-auto vh-100">
        <style>
            .collapsible {
              background-color: #4169e1;
              color: white;
              cursor: pointer;
              width: 100%;
              border: none;
              text-align: left;
              outline: none;
              font-size: 15px;
            }
            
            
            
            .content {                
              display: none;
              overflow: hidden;
              background-color: #f1f1f1;
            }
            </style>
            
          {% comment %} ==================== {% endcomment %}
          <hr class="dark horizontal my-1" />
          <h3 class="text-white text-center">Curriculum</h3>
          {% for i in lesson %}
            <button type="button" class="collapsible btn btn-primary btn-lg">Section {{ i.name }}</button>
            <div class="content">
              {% for j in i.video_set.all %}
              <div class="card mb-1 p-0" style="max-width: 100%;">
                <div class="row no-gutters">
                  <div class="col-md-4 text-center justify-content-center ml-2">
                    <img src="{{j.thumbnail.url}}" class="card-img p-2" alt="..." style="max-width: 100px; max-height:60px;">
                  </div>
                  <div class="col-md-8 mx-auto">
                    <div class="card-body">
                      <h5 class="card-title text-left">{{j.title}}</h5>
                      <a href="javascript:void(0);" class="btn btn-success" onclick="playVideo('{{ j.video_url }}')">Play Now</a>
                      {{ j.videourl }}
                    </div>
                  </div>
                </div>
              </div>
                <hr>
                <!-- Display other video information as needed -->
              {% endfor %}
            </div>
          {% endfor %}
          
          </div>
          <script>
            function playVideo(videoUrl) {
              var videoPlayer = document.getElementById("videoPlayer");
              videoPlayer.src = videoUrl;
            }
            var coll = document.getElementsByClassName("collapsible");
            var i;

            for (i = 0; i < coll.length; i++) {
              coll[i].addEventListener("click", function() {
                this.classList.toggle("active");
                var content = this.nextElementSibling;
                if (content.style.display === "block") {
                  content.style.display = "none";
                } else {
                  content.style.display = "block";
                }
              });
            }
            </script>
    </div>
  </div>
</div>
{% endblock%}

LMS/templates/Student/myblogs.html
{% extends 'components/dashboard/base.html'%}
{%block title%}Learning | Skylearner {% endblock %}
{% block sub_title %}<h6 class="font-weight-bolder mb-0">My Blogs</h6>{% endblock %}
{% load static %}

{% block content %}

<a class="btn btn-primary btn-lg" href="{% url 'addblog' %}">Create New Blog <a> 
<div class="row">
  <div class="col-lg-12 position-relative z-index-2">
    <div class="row mt-5">
        {% for i in blog %}
        {% if i.user.username == user.username %}
        <div class="col-lg-4 mt-5 mt-lg-0">
          <div class="card mt-5" data-animation="true">
            <div
              class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <a class="d-block blur-shadow-image">
                {% if i.status == 'PUBLISH' %}
                <span class="badge rounded-pill badge-success position-absolute">{{i.status}}</span>
                {% elif i.status == 'DRAFT' %}
                <span class="badge rounded-pill badge-danger position-absolute">{{i.status}}</span>
                {% elif i.status == 'PENDING' %}
                <span class="badge rounded-pill badge-warning position-absolute">{{i.status}}</span>
                {% endif %}
                <img
                  src="{{ i.featured_image.url }}"
                  alt="img-blur-shadow"
                  class="img-fluid shadow border-radius-lg" />
              </a>
              
              <div
                class="colored-shadow"
                style="
                  background-image: url('{{ i.featured_image.url }}
                "></div>
            </div>
            <div class="card-body text-center">
              
              <div class="d-flex mt-n6 mx-auto">
                <a
                  class="btn btn-link text-primary ms-auto border-0"
                  data-bs-toggle="tooltip"
                  data-bs-placement="bottom"
                  title="Refresh">
                  <i class="material-icons text-lg">refresh</i>
                </a>
                <button
                  class="btn btn-link text-info me-auto border-0"
                  data-bs-toggle="tooltip"
                  data-bs-placement="bottom"
                  title="Edit">
                  <i class="material-icons text-lg">edit</i>
                </button>
              </div>
              <h5 class="font-weight-normal mt-3">
                <a href="javascript:;">{{ i.title }}</a>
              </h5>
              <p class="mb-0">
                {{i.description | safe | truncatewords:20}}
              </p>
            </div>
            <hr class="dark horizontal my-0" />
            <div class="card-footer d-flex">
              <a href ="{{i.edit_blog_url}}" class="btn btn-warning btn-sm m-auto">Edit</a>
              <form method="post" action="{% url 'blog_status_function' blog_id=i.id %}">
                {% csrf_token %}
                
                
                {% if i.status == 'DRAFT' %}
                    <button type="submit" class="btn btn-success btn-sm m-auto" name="new_status" value="PUBLISH">Publish</button>
                {% endif %}
                <button type="submit" class="btn btn-info btn-sm m-auto" name="new_status" value="DRAFT">Save Draft</button>
                
                <button type="submit" class="btn btn-danger btn-sm m-auto" name="new_status" value="DELETE">Delete</button>
            </form>
            
            </div>
            <div class="card-footer my-0 d-flex">
              <i
                class="material-icons position-relative ms-auto text-lg me-1 my-auto"
                >account_circle</i
              >
              <p class="text-sm my-auto">{{i.user}}</p>
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
      </div>
  </div>
</div>
{% endblock %}

LMS/templates/Student/mycart.html
{% extends 'components/dashboard/base.html'%} 
{%block title%}My Cart | Skylearner {% endblock %}
{% load static %} 
{%block content%}
<div class="container mt-5" bis_skin_checked="1">
  <h2 class="my-5 text-center">Course Cart</h2>
  <div class="row" bis_skin_checked="1">
    <div class="col-12 col-lg-7" bis_skin_checked="1">
      <div class="d-block d-md-flex" bis_skin_checked="1">
        <img
          class="w-50 w-md-30 rounded-3"
          src="{{course.featured_image.url}}"
          alt="watch-image" />
        <div class="w-100 w-md-50 ps-md-4" bis_skin_checked="1">
          <h6 class="text-lg mb-1">{{course.title}}</h6>
          
          <div class="d-flex align-items-center mt-6" bis_skin_checked="1">
            <i class="fas fa-check text-lg text-success" aria-hidden="true"></i>
            <p class="mb-0 ms-2 text-sm">In Stock </p>
          </div>
        </div>
        
        <p class="ms-3">Rs.{{course.price}}</p>
        <div class="w-10 text-end" bis_skin_checked="1">
          <a href="#"><i class="fas fa-times ms-3" aria-hidden="true"></i></a>
        </div>
      </div>
      <hr class="horizontal dark my-4" />
      
      <hr class="horizontal dark my-4" />
      
    </div>
    <div class="col-12 col-lg-5 mt-5 mt-lg-0" bis_skin_checked="1">
      <div class="card shadow-xs border bg-gray-100" bis_skin_checked="1">
        <div class="card-body p-lg-5" bis_skin_checked="1">
          <h5 class="mb-4">Order Summary</h5>
          <ul class="list-unstyled">
            <li class="mt-2">
              <div class="d-flex justify-content-between" bis_skin_checked="1">
                <p class="opacity-8">Subtotal </p>
                <p class="fw-bold opacity-8">Rs.{{course.price}}</p>
              </div>
            </li>
            
            <li class="mt-4">
              <div class="d-flex justify-content-between" bis_skin_checked="1">
                <h5 class="">Total</h5>
                <h5 class="">Rs. {{course.price}}</h5>
              </div>
            </li>
          </ul>
          {% for product in products %}
    {% if product.product_identity == course.id  and username|striptags|lower == product.user|striptags|lower %}
        <a class="btn btn-white btn-lg w-100" href="{{ course.checkout_url }}">Already Enrolled</a>
    {% else %}
        <a class="btn btn-white btn-lg w-100 bg-success text-white" href="{{ course.checkout_url }}">Buy Now</a>
    {% endif %}
{% endfor %}

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

LMS/templates/Student/mycourses.html
{% extends 'components/dashboard/base.html'%}
{%block title%}Learning | Skylearner {% endblock %}
{% block sub_title %}<h6 class="font-weight-bolder mb-0">My Courses</h6>{% endblock %}
{% load static %}

{% block content %}
{% if user.is_instructor %}
<a class="btn btn-primary btn-lg" href="{% url 'addcourse' %}">Create New Course<a> 

<div class="row">
  <div class="col-lg-12 position-relative z-index-2">
    <div class="row mt-5">
      {% for i in course %}
      {% if i.instructor.username == user.username %}
        <div class="col-lg-4 mt-5 mt-lg-0">
          <div class="card mt-5" data-animation="true">
            
            <div
              class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              
              <a class="d-block blur-shadow-image">
                {% if i.status == 'PUBLISH' %}
                <span class="badge rounded-pill badge-success position-absolute">{{i.status}}</span>
                {% elif i.status == 'DRAFT' %}
                <span class="badge rounded-pill badge-danger position-absolute">{{i.status}}</span>
                {% elif i.status == 'PENDING' %}
                <span class="badge rounded-pill badge-warning position-absolute">{{i.status}}</span>
                {% endif %}
                <img
                  src="{{ i.featured_image.url }}"
                  alt="img-blur-shadow"
                  class="img-fluid shadow border-radius-lg" />
              </a>
              <div
                class="colored-shadow"
                style="
                  background-image: url('{{ i.featured_image.url }}
                "></div>
            </div>
            <div class="card-body text-center">
              
              <div class="d-flex mt-n6 mx-auto">
                <a
                  class="btn btn-link text-primary ms-auto border-0"
                  data-bs-toggle="tooltip"
                  data-bs-placement="bottom"
                  title="Refresh">
                  <i class="material-icons text-lg">refresh</i>
                </a>
                <button
                  class="btn btn-link text-info me-auto border-0"
                  data-bs-toggle="tooltip"
                  data-bs-placement="bottom"
                  title="Edit">
                  <i class="material-icons text-lg">edit</i>
                </button>
              </div>
              <h5 class="font-weight-normal mt-3">
                <a href="javascript:;">{{ i.title }}</a>
              </h5>
              <p class="mb-0">
                {{i.description | safe | truncatewords:20}}
              </p>
            </div>
            <hr class="dark horizontal my-0" />
            <div class="card-footer d-flex">
              <a href ="{{i.edit_blog_url}}" class="btn btn-warning btn-sm m-auto">Edit</a>
              <form method="post" action="{% url 'course_status_function' course_id=i.id %}">
                {% csrf_token %}
                {% if i.status == 'DRAFT' %}
                    <button type="submit" class="btn btn-success btn-sm m-auto" name="new_status" value="PUBLISH">Publish</button>
                {% else %}
                <button type="submit" class="btn btn-info btn-sm m-auto" name="new_status" value="DRAFT">Save Draft</button>
                {% endif%}
                <button type="submit" class="btn btn-danger btn-sm m-auto" name="new_status" value="DELETE">Delete</button>
            </form>
            
          </div>
           
          <div class="card-footer my-0 d-flex">
            <i
              class="material-icons position-relative ms-auto text-lg me-1 my-auto"
              >account_circle</i
            >
            <p class="text-sm my-auto">{{i.instructor}}</p>
          </div>
        </div>
        </div>
        
        {% endif %}
        
        {% endfor %}
      </div>
  </div>
</div>

{% endif %}


{% if user.is_student %}
<div class="row">
  <div class="col-lg-12 position-relative z-index-2">
    <div class="row mt-5">
      {% for i in enroll %}
      {% if i.user|striptags|lower == username|striptags|lower %}
      
        <div class="col-lg-4 mt-5 mt-lg-0">
          <div class="card mt-5" data-animation="true">
            <div
              class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <a class="d-block blur-shadow-image">
                <img
                  src="{{i.course.featured_image.url}}"
                  alt="{{i.course.featured_image.url}}"
                  class="img-fluid shadow border-radius-lg" />
              </a>
              <div
                class="colored-shadow"
                style="
                  background-image: url('{{i.course.featured_image.url}}')%}
                "></div>
            </div>
            <div class="card-body text-center">
              
              <h5 class="font-weight-normal mt-3">
                <a href="javascript:;">{{i.course.title}}</a>
              </h5>
              <p class="mb-0">
                {{i.course.description | safe | truncatewords:50}}
              </p>
            </div>
            <hr class="dark horizontal my-0" />
            <div class="card-footer d-flex">
              <a class="btn btn-outline-danger" href="{{i.course.learning_area_url}}">Start Learning</a>
              <i
                class="material-icons position-relative ms-auto text-lg me-1 my-auto"
                >account_circle</i
              >
              <p class="text-sm my-auto">{{i.course.instructor}}</p>
            </div>
          </div>
        </div>     
        {% endif%}   
        {% endfor %}
      </div>
  </div>
</div>
{% endif %}
{% endblock %}

LMS/templates/Student/myfeedbacks.html
{% extends 'components/dashboard/base.html'%}
{%block title%}My Feedbacks | Skylearner {% endblock %}
{% block sub_title %}<h6 class="font-weight-bolder mb-0">Feedbacks</h6>{% endblock %}
{% load static %}

{%block content%}

{% endblock%}

LMS/templates/Student/notifications.html
{% extends 'components/dashboard/base.html'%} {%block title%}Message |
Skylearner {% endblock %} {% load static %} {%block content%}
<h1>Notofications</h1>

{% endblock %}