LMS/LMS/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.models import User

from django_otp.admin import OTPAdminSite
from django_otp.plugins.otp_totp.models import TOTPDevice
from django_otp.plugins.otp_totp.admin import TOTPDeviceAdmin

class OTPAdmin(OTPAdminSite):
    pass

# Create an instance of your custom admin site
admin_site = OTPAdmin(name='OTPAdmin')

# Register User and TOTPDevice with your custom admin site
admin_site.register(User)
admin_site.register(TOTPDevice, TOTPDeviceAdmin)

urlpatterns = [
    path('admin/', admin_site.urls),  # Use your custom admin site
    path('dadmin/', admin.site.urls),  # Use the default admin site
    path('', include('lmsapp.urls')),
]

LMS/lmsapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.dispatch import receiver
from ckeditor.fields import RichTextField


# Create your models here.
class User(AbstractUser): 
    STATUS = (
        ('STUDENT','STUDNET'),        
        ('PENDING', 'PENDING'),
        ('INSTRUCTOR', 'INSTRUCTOR'),
    )   
    profile_image = models.ImageField(upload_to="Images/profile", null=True, blank=True, default='img/team-1.jpg')
    is_manager = models.BooleanField('Is manager', default=False)
    is_instructor = models.BooleanField('Is instructor', default=False)
    is_student = models.BooleanField('Is student', default=True)
    user_bio = models.TextField(default='', max_length=200, null=True, blank=True)
    email_token = models.UUIDField(default=uuid.uuid4, editable=False)
    is_verified = models.BooleanField(default=False)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    status = models.CharField(choices=STATUS,max_length=100,null=True, default="STUDENT")

    def account_detail_url(self):
        from django.urls import reverse
        return reverse("accdetails", kwargs={'slug': self.slug})

class Categories (models.Model):
    icon = models.CharField(max_length=200, null=True)
    name = models.CharField(max_length=100)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    def __str__(self):
        return self.name

class Course(models.Model): 
    STATUS = (
        ('PUBLISH','PUBLISH'),
        ('DRAFT', 'DRAFT'),        
        ('PENDING', 'PENDING'),
    )
    title = models.CharField(max_length=500)
    date = models.DateField(auto_now_add=True)
    featured_image = models.ImageField(upload_to="Images/Featured_Image/featured_img",null=True, blank=True)
    instructor = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    category = models.ForeignKey(Categories,on_delete=models.CASCADE)
    featured_video = models.CharField(max_length=300,null=True)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    status = models.CharField(choices=STATUS,max_length=100,null=True)
    description = RichTextField(blank=True, null=True)
    price = models.IntegerField(null=True,default=0)
    discount = models.IntegerField(null=True)

    def __str__(self):
        return self.title
    
    def course_url(self):
        from django.urls import reverse
        return reverse("coursedetails", kwargs={'slug': self.slug})

    def checkout_url(self):
        from django.urls import reverse
        return reverse("checkout", kwargs={'slug': self.slug})

    def cart_url(self):
        from django.urls import reverse
        return reverse("cart", kwargs={'slug': self.slug})

    def edit_course_url(self): 
        from django.urls import reverse
        return reverse("editcourse", kwargs={'slug': self.slug})

    def learning_area_url(self): 
        from django.urls import reverse
        return reverse("learning_area", kwargs={'slug': self.slug})

    def add_lesson_url(self): 
        from django.urls import reverse
        return reverse("add_lesson", kwargs={'slug': self.slug})

    


class Blog(models.Model):
    STATUS = (
        ('PUBLISH','PUBLISH'),
        ('DRAFT', 'DRAFT'),
        ('PENDING', 'PENDING'),
    )
    title = models.CharField(max_length=500)
    date = models.DateField(auto_now_add=True)
    featured_image = models.ImageField(upload_to="Images/Featured_Image/Blog",null=True, blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    category = models.ForeignKey(Categories,on_delete=models.CASCADE)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    status = models.CharField(choices=STATUS,max_length=100,null=True)
    description = RichTextField(blank=True, null=True)
    

    def __str__(self):
        return self.title

    def edit_blog_url(self):
        from django.urls import reverse
        return reverse("editblog", kwargs={'slug': self.slug})
    
    def blog_url(self):
        from django.urls import reverse
        return reverse("blogdetails", kwargs={'slug': self.slug})



# ==================================slug creator=======================
def create_slug(instance, new_slug=None):
    if isinstance(instance, (Course, Blog)):
        source_field = 'title'
    elif isinstance(instance, User):
        source_field = 'username'
    elif isinstance(instance, Categories):
        source_field = 'name'
    else:
        raise ValueError("Unsupported model type for slug generation")

    
    slug = slugify(getattr(instance, source_field))

    if new_slug is not None:
        slug = new_slug

    model_class = instance.__class__
    qs = model_class.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()

    if exists:
        new_slug = f"{slug}-{qs.first().id}"
        return create_slug(instance, new_slug=new_slug)
    return slug

@receiver(pre_save, sender=Course)
@receiver(pre_save, sender=Blog)
@receiver(pre_save, sender=Categories)
@receiver(pre_save, sender=User)
def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__ (self):
        return self.name + " - " + self.course.title 

class Video(models.Model):
    serial_number = models.IntegerField(null=True)
    thumbnail = models.ImageField(upload_to="Images/Lesson", null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    title = models.CharField(max_length = 100)
    video_url = models.CharField(max_length= 200)
    time_duration = models.FloatField(null=True)
    preview = models.BooleanField(default=False) 

    def __str__(self):
        return self.title


class DigitalProduct(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    product_identity = models.IntegerField(null=True,default=0)
    product_name = models.CharField(max_length=255)
    transaction_id = models.CharField(max_length=255, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    mobile = models.CharField(max_length=15, default="980000000", null=True) 

    def __str__(self):
        return f'{self.user.username} - {self.product_name} - Transaction ID: {self.transaction_id}'

class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_messages')
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __str__(self):
        return f"{self.sender.username} to {self.receiver.username} - {self.timestamp}"


# Recommendations
class SearchQuery(models.Model):
    query = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.query




# ===========certificate:
class Certificate(models.Model):
    username = models.CharField(max_length=255)
    course_name = models.CharField(max_length=255)
    instructor_name = models.CharField(max_length=255)


# comment
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course_title = models.CharField(max_length=255)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.course_title} - {self.created_at}"

LMS/templates/required_login_pages/add_lesson.html
{% extends 'components/dashboard/base.html'%} {%block title%}Add Lesson |
Skylearner {% endblock %} {% block sub_title %}
<h6 class="font-weight-bolder mb-0">Add Lesson</h6>
{% endblock %} {% load static %} {% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Course name: {{course.title}} </h1>
    <div class="row">
        <div class="col">
           <h3> Add Lesson</h3>
           <button type="button" class="btn bg-gradient-success mx-auto btn-lg" data-bs-toggle="modal" data-bs-target="#course_modal">
            Add Lessons
          </button>
          <ul class="list-group">
            
            {% for i in lessons %}
            {% comment %} {% if not i%} {% endcomment %}
            <li class="list-group-item ">Lesson Name: <strong>{{i.name}}</strong> 
                <button type="button" class="btn bg-gradient-danger mx-auto" data-bs-toggle="modal" data-bs-target="#lesson_modal_{{ i.id }}">
                    Add Chapters
                  </button>
            </li>


            <div class="modal fade" id="lesson_modal_{{ i.id }}" tabindex="-1" role="dialog" aria-labelledby="lesson_modal_{{ i.id }}Label" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="lesson_modal_{{ i.id }}Label">{{i.name}}</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <form method="post" action="{% url 'add_chapter' lesson_id=i.id %}" enctype="multipart/form-data">
                        {% csrf_token %}
                    <div class="modal-body">
                        <label for="title">Course Title:</label>
                        <input class="form-control form-control-lg border" type="text"
                           value="{{course.title}}" name="course_title" readonly/>
                        
                        <input class="form-control form-control-lg border" type="hidden" value="{{course.id}}" name="course_id"/>
                        <label for="title">Lesson Title:</label>
                        <input class="form-control form-control-lg border" type="text"
                           value="{{i.name}}" readonly/>
                        <label for="serial">Serial Number:</label>
                        <input class="form-control form-control-lg border" type="text"
                          id="serial" name="serial"/>
                           <label for="title">Chapter Title:</label>
                        <input class="form-control form-control-lg border" type="text"
                          id="title" name="title"/>
                          <label for="url">Video URL:</label>
                        <input class="form-control form-control-lg border" type="text"
                          id="url" name="url"/>
                          <label for="Thumbnail">Thumbnail</label>
                         <input type="file" class="form-control-file" id="Thumbnail" name="Thumbnail">
                         <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">Preview</label>
                          </div>
                        
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn bg-gradient-success" data-bs-dismiss="modal">Close</button>
                    
                    <button type="submit" class="btn bg-gradient-danger" data-bs-dismiss="modal">Yes</button>
                    </form>
                    </div>
                  </div>
                </div>
              </div>
            

              {% comment %} {% endif %} {% endcomment %}
            {% endfor %}
            
          </ul>
          {% comment %} ==========Modal for Lesson============ {% endcomment %}
          <div class="modal fade" id="course_modal" tabindex="-1" role="dialog" aria-labelledby="course_modalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="course_modalLabel">Add Lesson</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                
                <form method="post" action="{% url 'add_lesson_name' course_id=course.id %}">
                    {% csrf_token %}
                <div class="modal-body">
                    <label for="title">Course Title:</label>
                    <input class="form-control form-control-lg border" type="text" value="{{course.title}}" readonly/>
                    <label for="title">Lesson Title:</label>
                    <input class="form-control form-control-lg border" type="text"
                      id="title" name="title"/>
                </div>
                <div class="modal-footer">
                        <button type="submit" class="btn bg-gradient-success" data-bs-dismiss="modal">Yes</button>
                    </form>
                  <button type="button" class="btn bg-gradient-danger" data-bs-dismiss="modal">Close</button>
                  
                </div>
                
              </div>
            </div>
          </div>
        </div>
        
          
          {% comment %} ==========Modal for Chapter============ {% endcomment %}
          

   
  
  {% endblock%}
</div>

LMS/templates/required_login_pages/addblog.html
{% extends 'components/dashboard/base.html'%} {%block title%}Learning |
Skylearner {% endblock %} {% block sub_title %}
<h6 class="font-weight-bolder mb-0">Add New Blog</h6>
{% endblock %} {% load static %} 
{% block content %}

<form method="post" action="{% url 'create_blog' %}" enctype="multipart/form-data" id="blogForm">
  {% csrf_token %}
  <div class='row'>
    <div class='col-8'>
      <div class="form-group">
        <label for="title">Blog Title</label>
        <input class="form-control form-control-lg border" type="text" placeholder="" id="title" name="title" />
        <label for="slug">Slug</label>
        <input class="form-control form-control-lg border" type="text" placeholder="" id="slug" value="Slug Will Automatically Added" readonly />
        <div class="row">
          <div class="col">
            <label for="inputState">Category</label>
            <select id="inputState" class="form-control form-control-lg border" name="category">
              {% for i in category %}
                <option value="{{ i.id }}">{{ i.name }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <label for="exampleFormControlTextarea1">Blog Descriptions</label>
        <textarea class="form-control form-control-lg border" id="exampleFormControlTextarea1" rows="10" name="description" required></textarea>
      </div>
    </div>
    <div class="col-4">
      <hr class="dark horizontal my-1" />
      <label for="id_featured_image" class="mt-5">Choose Featured Image</label>
      <input type="file" class="form-control-file" id="id_featured_image" name="featured_image" />
    </div>
  </div>
  <hr class="dark horizontal my-3" />
  <div class="card-footer d-flex">
    <button type="button" class="btn btn-warning btn-lg mx-auto" onclick="setBlogStatus('DRAFT')">Save as Draft</button>
    <button type="button" class="btn btn-success btn-lg mx-auto" onclick="setBlogStatus('PUBLISH')">Publish</button>
    <input type="hidden" id="blogStatus" name="status" value="DRAFT">
  </div>
</form>

<script>
  function setBlogStatus(status) {
      document.getElementById('blogStatus').value = status;
      document.getElementById('blogForm').submit();
  }
</script>




{% comment %} <form method="post" method="post" action="{% url 'create_blog' %}" enctype="multipart/form-data">
  {% csrf_token %}
    <div class='row'>
        <div class='col-8'>
  <div class="form-group">
    <label for="title">Blog Title</label>
    <input
      class="form-control form-control-lg border"
      type="text"
      placeholder=""
      id="title" name="title" />
    <label for="slug">Slug</label>
    <input
      class="form-control form-control-lg border"
      type="text"
      placeholder=""
      id="slug" value="Slug Will Automatically Added"
      readonly />
    <div class="row">
      <div class="col">
        <label for="inputState">Category</label>
        <select id="inputState" class="form-control form-control-lg border" name="category">
            {% for i in category %}
                <option value="{{ i.id }}">{{ i.name }}</option>
            {% endfor %}
        </select>
      </div>
    </div>
  </script>
    <label for="exampleFormControlTextarea1">Blog Descriptions</label>
    <textarea class="form-control form-control-lg border" id="exampleFormControlTextarea1" rows="10" name="description" required></textarea>
    
  </div>

</div>
<div class="col-4">
    <hr class="dark horizontal my-1" />
    <label for="id_featured_image" class="mt-5">Choose Featured Image</label>
    <input type="file" class="form-control-file" id="id_featured_image" name="featured_image" />
</div>
</div>


<hr class="dark horizontal my-3" />
<div class="card-footer d-flex">
  <button type="button" class="btn btn-warning btn-lg mx-auto" onclick="setBlogStatus('DRAFT')">Save as Draft</button>
  <button type="button" class="btn btn-success btn-lg mx-auto" onclick="setBlogStatus('PUBLISH')">Publish</button>

  <input type="hidden" id="blogStatus" name="status" value="DRAFT">
</div>
</form>
<script>
  function setBlogStatus(status) {
      document.getElementById('blogStatus').value = status;
      document.getElementById('blogForm').submit();
  }
</script> {% endcomment %}
{% endblock %}

LMS/templates/required_login_pages/addcourse.html
{% extends 'components/dashboard/base.html'%} {%block title%}Add Course |
Skylearner {% endblock %} {% block sub_title %}
<h6 class="font-weight-bolder mb-0"> Add New Course</h6>
{% endblock %} {% load static %} 
{% block content %}
<form method="post"action="{% url 'create_course' %}" enctype="multipart/form-data" id="courseForm">
  {% csrf_token %}
    <div class='row'>
        <div class='col-8'>
  <div class="form-group">
    <label for="title">Course Title</label>
    <input
      class="form-control form-control-lg border"
      type="text"
      placeholder=""
      id="title" name="title" />
    <label for="slug">Slug</label>
    <input
      class="form-control form-control-lg border"
      type="text"
      placeholder=""
      id="slug" value="Slug Will Automatically Added"
      readonly />
    <div class="row">
        <div class="col">
            <label for="price">Original Price</label>
            <input
              type="text"
              class="form-control form-control-lg border"
              id="price" name="price"/>
          </div>
          <div class="col">
            <label for="dpercent">Discount %</label>
            <input
              type="text"
              class="form-control form-control-lg border"
              id="dpercent" name="discount" />
          </div>
      <div class="col">
        <label for="inputState">Category</label>
        <select id="inputState" class="form-control form-control-lg border" name="category">
          {% for i in category %}
            <option value="{{ i.id }}">{{ i.name }}</option>
          {% endfor %}
        </select>
      </div>
    </div>
    <label for="exampleFormControlTextarea1">Course Description</label>
    <textarea class="form-control form-control-lg border" id="exampleFormControlTextarea1" rows="10" name="description" required></textarea>
  </div>

</div>
<div class="col-4">
    <hr class="dark horizontal my-1" />
    <label for="image" class="mt-5">Choose Featured Image</label>
    <input type="file" class="form-control-file" id="image" name="featured_image" />
</div>
</div>


<hr class="dark horizontal my-3" />
<div class="card-footer d-flex">
  <button type="button" class="btn btn-warning btn-lg mx-auto" onclick="setBlogStatus('DRAFT')">Save as Draft</button>
  <button type="button" class="btn btn-success btn-lg mx-auto" onclick="setBlogStatus('PUBLISH')">Publish</button>
  <input type="hidden" id="blogStatus" name="status" value="DRAFT">
</div>
</form>
<script>
  function setBlogStatus(status) {
      document.getElementById('blogStatus').value = status;
      document.getElementById('courseForm').submit();
  }
</script>
{% endblock %}

LMS/templates/required_login_pages/edit_blog.html
{% extends 'components/dashboard/base.html'%} {%block title%}Learning |
Skylearner {% endblock %} {% block sub_title %}
<h6 class="font-weight-bolder mb-0">Edit Blog</h6>
{% endblock %} {% load static %} {% block content %}
<form method="post"  action="{% url 'update_blog' blog.id %}" enctype="multipart/form-data" >
  {% csrf_token %}
    <div class='row'>
        <div class='col-8'>
  <div class="form-group">
    <label for="title">Blog Title</label>
    <input
      class="form-control form-control-lg border"
      type="text"
      id="title" value="{{blog.title}}" name="title" />
    <label for="slug">Slug</label>
    <input
      class="form-control form-control-lg border"
      type="text"
      placeholder=""
      id="slug" value="{{blog.slug}}"
      readonly />
    <div class="row">
      <div class="col">
        <label for="inputState">Category</label>
        <select id="inputState" class="form-control form-control-lg border" name="category">
            {% for category_instance in category %}
                <option {% if category_instance.name == blog.category %}selected{% endif %}
                        value="{{ category_instance.name }}">{{ category_instance.name }}</option>
            {% endfor %}
        </select>
    </div>    </div>
    <label for="exampleFormControlTextarea1">Blog Description</label>
    <textarea class="form-control form-control-lg border" id="exampleFormControlTextarea1" name="description" rows="10">{{blog.description}}</textarea>
  </div>

</div>
<div class="col-4"><img src="{{blog.featured_image.url}}" class="img-fluid" alt="Wild Landscape" />
    <hr class="dark horizontal my-1" />
    <label for="image" class="mt-5">Choose Image</label>
    <input type="file" class="form-control-file" id="image" name="featured_image" />
</div>
</div>

<hr class="dark horizontal my-3" />
<div class="card-footer d-flex">
  <button type="submit" class="btn btn-danger btn-lg mx-auto">Save</button>

  <p class="text-sm my-auto">{{i.instructor}}</p>
</div>
</form>
{% endblock %}

LMS/templates/required_login_pages/edit_course.html
{% extends 'components/dashboard/base.html'%} {%block title%}Learning |
Skylearner {% endblock %} {% block sub_title %}
<h6 class="font-weight-bolder mb-0">Edit Course</h6>
{% endblock %} {% load static %} {% block content %}
<form method="post"  action="{% url 'update_course' course.id %}" enctype="multipart/form-data" >
  {% csrf_token %}
    <div class='row'>
        <div class='col-8'>
  <div class="form-group">
    <label for="title">Course Title:</label>
    <input
      class="form-control form-control-lg border"
      type="text"
      placeholder=""
      id="title" value="{{course.title}}" name="title"/>
    <label for="slug">Slug</label>
    <input
      class="form-control form-control-lg border"
      type="text"
      placeholder=""
      id="slug" value="{{course.slug}}"
      readonly />
    <div class="row">
      <div class="col">
        <label for="price">Original Price</label>
        <input
          type="text"
          class="form-control form-control-lg border"
          id="price" value="{{course.price}}" name="price"/>
      </div>
      <div class="col">
        <label for="dpercent">Discount %</label>
        <input
          type="text"
          class="form-control form-control-lg border"
          id="dpercent" value="{{course.discount}}" name="discount" />
      </div>
      <div class="col">
        <label for="inputState">Category</label>
        <select id="inputState" class="form-control form-control-lg border" name="category">
            {% for category_instance in category %}
                <option {% if category_instance.name == course.category %}selected{% endif %}
                        value="{{ category_instance.name }}">{{ category_instance.name }}</option>
            {% endfor %}
        </select>
    </div>
    </div>
    <label for="exampleFormControlTextarea1">Course Description</label>
    <textarea class="form-control form-control-lg border" id="exampleFormControlTextarea1" 
    rows="10" name="description">{{course.description}}</textarea>
  </div>

</div>
<div class="col-4"><img src="{{course.featured_image.url}}" class="img-fluid" alt="Wild Landscape" />
    <hr class="dark horizontal my-1" />
    <label for="image" class="mt-5">Choose Image</label>
    <input type="file" class="form-control-file" id="image" name="featured_image" />
</div>
</div>


<hr class="dark horizontal my-3" />
<div class="card-footer d-flex">
  <button type="submit" class="btn btn-danger btn-lg mx-auto" >Save As Draft</button>

  <a class="btn btn-success mx-auto btn-lg">Publish Course</a>

  <p class="text-sm my-auto">{{i.instructor}}</p>
</div>
</form>
{% endblock %}